// ------------------------------------------------------------------------------
//  <autogenerated>
//      This code was generated by a tool.
//      Mono Runtime Version: 4.0.30319.42000
// 
//      Changes to this file may cause incorrect behavior and will be lost if 
//      the code is regenerated.
//  </autogenerated>
// ------------------------------------------------------------------------------

namespace OpenGeoDB.Resources {
    using System;
    using System.Reflection;
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Strings {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("OpenGeoDB.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static string CitiesViewModel_Title {
            get {
                return ResourceManager.GetString("CitiesViewModel.Title", resourceCulture);
            }
        }
        
        internal static string ZipCodesViewModel_Title {
            get {
                return ResourceManager.GetString("ZipCodesViewModel.Title", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_Title {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.Title", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_SectionInformation {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.SectionInformation", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_SectionNearby {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.SectionNearby", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_HintZip {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.HintZip", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_HintCity {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.HintCity", resourceCulture);
            }
        }
        
        internal static string ZipCodeViewModel_HintLoсation {
            get {
                return ResourceManager.GetString("ZipCodeViewModel.HintLoсation", resourceCulture);
            }
        }
    }
}
